flowchart TD

START[Старт игры] --> B{Выбор класса}

B -->|Доктор Фальк| D 
B -->|Монах Мильтон| D

D[Путь в собор]
D --> E[Встреча с нищим]

E --> F{Класс?}

F -->|Монах| G1[Пройти мимо]
F -->|Доктор| H{Дать монетку?}

H -->|Дать монетку| G2[Нищий запоминает вас]
H -->|Игнор| G1[Пройти мимо]

G1 --> I[Вход в собор]
G2 --> I

I --> J{hero.dream > 0?}

J -->|Да| K[Первое проявление сна]
J -->|Нет| L[Без проявления сна]

K --> M[Разговор с отцом Стефаном]
L --> M

M --> N{Класс?}

N -->|Доктор Фальк| O[Храмовая лечебница]
N -->|Монах Мильтон| P[Комната допросов]

O --> O1[Осмотр пациентов]
P --> P1[Разговор с культистом]

O1 --> Q[Хор замолкает]
P1 --> Q

Q --> R[Герой врывается в зал]

R --> S[Спящие покидают собор]

S --> T[Выход из собора вместе со Стефаном]

T --> U[Калека нападает и вырубает Стефана]

U --> V{Давал монетку ранее?}

V -->|Да| W1[Калека не нападает]
V -->|Нет| W2[Калека вырубает героя]

W1 --> Y[Герой тащит Стефана в собор и вырубается]
W2 --> END[Конец пролога]
Y --> END[Конец пролога]

class START,END act
class B,F,H,J,N,V condition
class C,C1,C2,D,E,F,G1,G2,G3,I,L,M,O,O1,P,P1,Q,R,S,T,U,W1,Y,W2 neutral
class K dream

classDef act fill:#ffcc99,stroke:#cc6600,stroke-width:4px,color:#000
classDef condition fill:#ffcccc,stroke:#cc0000,stroke-width:3px,color:#000
classDef neutral fill:#fff2b2,stroke:#b38f00,stroke-width:2px,color:#000
classDef dream fill:#800080,stroke:#000,stroke-width:2px,color:#000

linkStyle default stroke-width:4px