# Картинки фонов
image morvein_start = im.Scale("bg/_start.png", 1920, 1080)

# Улицы
image morvein_streets = im.Scale("bg/morvein_streets.png", 1920, 1080)
image morvein_streets_dream = im.Scale("bg/morvein_streets_dream.png", 1920, 1080)
image morvein_well_alley = im.Scale("bg/morvein_well_alley.png", 1920, 1080)
image morvein_well_alley_dream = im.Scale("bg/morvein_well_alley_dream.png", 1920, 1080)
image morvein_night_alley = im.Scale("bg/morvein_night_alley.png", 1920, 1080)
image morvein_night_alley_dream = im.Scale("bg/morvein_night_alley_dream.png", 1920, 1080)
image morvein_tavern = im.Scale("bg/morvein_tavern.png", 1920, 1080)
image morvein_tavern_dream = im.Scale("bg/morvein_tavern_dream.png", 1920, 1080)
image morvein_merchant_shop = im.Scale("bg/act-1-furher/morvein_merchant_shop.png", 1920, 1080)
image morvein_merchant_shop_dream = im.Scale("bg/act-1-furher/morvein_merchant_shop.png", 1920, 1080)
image morvein_well_view = im.Scale("bg/morvein_well_view.png", 1920, 1080)
image morvein_well_view_dream = im.Scale("bg/morvein_well_view_dream.png", 1920, 1080)
image morvein_well_from_inside = im.Scale("bg/morvein_well_from_inside.png", 1920, 1080)
image morvein_well_from_inside_dream = im.Scale("bg/morvein_well_from_inside_dream.png", 1920, 1080)
image morvein_well_inside = im.Scale("bg/morvein_well_inside.png", 1920, 1080)
image morvein_well_inside_dream = im.Scale("bg/morvein_well_inside_dream.png", 1920, 1080)
image morvein_from_temple = im.Scale("bg/morvein_from_temple.png", 1920, 1200)
image morvein_from_temple_dream = im.Scale("bg/morvein_from_temple_dream.png", 1920, 1200)
image morvein_ancient_temple = im.Scale("bg/act-1-furher/morvein_ancient_temple.png", 1920, 1080)
image morvein_ancient_temple_dream = im.Scale("bg/act-1-furher/morvein_ancient_temple.png", 1920, 1080)

# Храм
image temple_inside = im.Scale("bg/temple_inside.png", 1920, 1080)
image temple_inside_dream = im.Scale("bg/temple_inside_dream.png", 1920, 1080)
image temple_outside = im.Scale("bg/temple_outside.png", 1920, 1080)
image temple_outside_dream = im.Scale("bg/temple_outside.png", 1920, 1080)
image temple_interrogation_room = im.Scale("bg/act-1-furher/temple_interrogation_room.png", 1920, 1200)
image temple_interrogation_room_dream = im.Scale("bg/act-1-furher/temple_interrogation_room.png", 1920, 1200)
image temple_hospital = im.Scale("bg/temple_hospital.png", 1920, 1200)
image temple_hospital_dream = im.Scale("bg/temple_hospital_dream.png", 1920, 1200)
image temple_stefan_office = im.Scale("bg/temple_stefan_office.png", 1920, 1200)
image temple_stefan_office_dream = im.Scale("bg/temple_stefan_office_dream.png", 1920, 1200)
image temple_council = im.Scale("bg/act-1-furher/temple_council.png", 1920, 1080)
image temple_council_dream = im.Scale("bg/act-1-furher/temple_council.png", 1920, 1080)
image temple_council_enter = im.Scale("bg/act-1-furher/temple_council_enter.png", 1920, 1080)
image temple_council_enter_dream = im.Scale("bg/act-1-furher/temple_council_enter.png", 1920, 1080)
image temple_archives = im.Scale("bg/act-1-furher/temple_archives.png", 1920, 1080)
image temple_archives_dream = im.Scale("bg/act-1-furher/temple_archives.png", 1920, 1080)
image temple_bed_view = im.Scale("bg/temple_bed_view.png", 1920, 1080)
image temple_bed_view_dream = im.Scale("bg/temple_bed_view_dream.png", 1920, 1080)
image temple_singer_cell = im.Scale("bg/act-1-furher/temple_singer_cell.png", 1920, 1080)
image temple_singer_cell_dream = im.Scale("bg/act-1-furher/temple_singer_cell.png", 1920, 1080)
image temple_underground_choir = im.Scale("bg/act-1-furher/temple_underground_choir.png", 1920, 1080)
image temple_underground_choir_dream = im.Scale("bg/act-1-furher/temple_underground_choir.png", 1920, 1080)
image temple_before_underground_choir = im.Scale("bg/act-1-furher/temple_before_underground_choir.png", 1920, 1080)
image temple_before_underground_choir_dream = im.Scale("bg/act-1-furher/temple_before_underground_choir.png", 1920, 1080)

# Особняк Триллианов
image trillian_house = im.Scale("bg/trillian_house.png", 1920, 1080)
image trillian_house_dream = im.Scale("bg/trillian_house_dream.png", 1920, 1080)
image trillian_drawing_room = im.Scale("bg/act-1-furher/trillian_drawing_room.png", 1920, 1080)
image trillian_drawing_room_dream = im.Scale("bg/act-1-furher/trillian_drawing_room.png", 1920, 1080)
image trillian_library = im.Scale("bg/act-1-furher/trillian_library.png", 1920, 1080)
image trillian_library_dream = im.Scale("bg/act-1-furher/trillian_library.png", 1920, 1080)
image trillian_altar_grotto = im.Scale("bg/act-1-furher/trillian_altar_grotto.png", 1920, 1080)
image trillian_altar_grotto_dream = im.Scale("bg/act-1-furher/trillian_altar_grotto.png", 1920, 1080)

# Однотонные фоны
image white = Solid("#ffffff")
image red = Solid("#8b0000")
image blue = Solid("#1b2a5b")
image green = Solid("#04ff00")
